FROM centos
RUN yum update -y
RUN yum install unzip -y
RUN yum install wget -y
RUN yum install httpd -y
WORKDIR /var/www/html
RUN wget https://www.tooplate.com/zip-templates/2119_gymso_fitness.zip
RUN unzip 2119_gymso_fitness.zip
RUN mv 2119_gymso_fitness mysite
ENTRYPOINT ["/usr/sbin/httpd", "-D", "FOREGROUND"]